SELECT
    COMPANY_CODE,
    FOUNDER,
    (SELECT COUNT(DISTINCT LEAD_MANAGER_CODE) FROM LEAD_MANAGER WHERE COMPANY_CODE = COMPANY.COMPANY_CODE) AS COUNT_LM,
    (SELECT COUNT(DISTINCT SENIOR_MANAGER_CODE) FROM SENIOR_MANAGER WHERE COMPANY_CODE = COMPANY.COMPANY_CODE) AS COUNT_SM,
    (SELECT COUNT(DISTINCT MANAGER_CODE) FROM MANAGER WHERE COMPANY_CODE = COMPANY.COMPANY_CODE) AS COUNT_M,
    (SELECT COUNT(DISTINCT EMPLOYEE_CODE) FROM EMPLOYEE WHERE COMPANY_CODE = COMPANY.COMPANY_CODE) AS COUNT_E
FROM COMPANY
ORDER BY COMPANY_CODE